################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.c \
../I-CUBE-Mongoose/App/mongoose_fs.c \
../I-CUBE-Mongoose/App/mongoose_glue.c \
../I-CUBE-Mongoose/App/mongoose_impl.c 

OBJS += \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.o \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.o \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.o \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.o 

C_DEPS += \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.d \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.d \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.d \
./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.o: ../Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.c Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -D__CCRX__ -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -DUSE_PWR_DIRECT_SMPS_SUPPLY -DUSE_NUCLEO_64 -DTX_INCLUDE_USER_DEFINE_FILE -DNX_SECURE_INCLUDE_USER_DEFINE_FILE -DNX_INCLUDE_USER_DEFINE_FILE -c -I../Core/Inc -I../I-CUBE-Mongoose/App -I"../Middlewares/I-CUBE-Mongoose/Network Library/Mongoose" -I../AZURE_RTOS/App -I../NetXDuo/App -I../NetXDuo/Target -I../../Drivers/BSP/Components/lan8742/ -I"../../Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/netxduo/common/drivers/ethernet/ -I../../Middlewares/ST/netxduo/addons/dhcp/ -I../../Middlewares/ST/netxduo/common/inc/ -I../../Middlewares/ST/netxduo/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/netxduo/nx_secure/inc/ -I../../Middlewares/ST/netxduo/nx_secure/ports/ -I../../Middlewares/ST/netxduo/crypto_libraries/inc/ -I../../Middlewares/ST/netxduo/crypto_libraries/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/threadx/common/inc/ -I"D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc/ -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32H7xx_Nucleo -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/I-CUBE-Mongoose/Network Library/Mongoose/mongoose.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.o: D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/CM7/I-CUBE-Mongoose/App/mongoose_fs.c Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -D__CCRX__ -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -DUSE_PWR_DIRECT_SMPS_SUPPLY -DUSE_NUCLEO_64 -DTX_INCLUDE_USER_DEFINE_FILE -DNX_SECURE_INCLUDE_USER_DEFINE_FILE -DNX_INCLUDE_USER_DEFINE_FILE -c -I../Core/Inc -I../I-CUBE-Mongoose/App -I"../Middlewares/I-CUBE-Mongoose/Network Library/Mongoose" -I../AZURE_RTOS/App -I../NetXDuo/App -I../NetXDuo/Target -I../../Drivers/BSP/Components/lan8742/ -I"../../Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/netxduo/common/drivers/ethernet/ -I../../Middlewares/ST/netxduo/addons/dhcp/ -I../../Middlewares/ST/netxduo/common/inc/ -I../../Middlewares/ST/netxduo/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/netxduo/nx_secure/inc/ -I../../Middlewares/ST/netxduo/nx_secure/ports/ -I../../Middlewares/ST/netxduo/crypto_libraries/inc/ -I../../Middlewares/ST/netxduo/crypto_libraries/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/threadx/common/inc/ -I"D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc/ -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32H7xx_Nucleo -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/I-CUBE-Mongoose/Network Library/Mongoose/mongoose_fs.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.o: D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/CM7/I-CUBE-Mongoose/App/mongoose_glue.c Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -D__CCRX__ -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -DUSE_PWR_DIRECT_SMPS_SUPPLY -DUSE_NUCLEO_64 -DTX_INCLUDE_USER_DEFINE_FILE -DNX_SECURE_INCLUDE_USER_DEFINE_FILE -DNX_INCLUDE_USER_DEFINE_FILE -c -I../Core/Inc -I../I-CUBE-Mongoose/App -I"../Middlewares/I-CUBE-Mongoose/Network Library/Mongoose" -I../AZURE_RTOS/App -I../NetXDuo/App -I../NetXDuo/Target -I../../Drivers/BSP/Components/lan8742/ -I"../../Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/netxduo/common/drivers/ethernet/ -I../../Middlewares/ST/netxduo/addons/dhcp/ -I../../Middlewares/ST/netxduo/common/inc/ -I../../Middlewares/ST/netxduo/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/netxduo/nx_secure/inc/ -I../../Middlewares/ST/netxduo/nx_secure/ports/ -I../../Middlewares/ST/netxduo/crypto_libraries/inc/ -I../../Middlewares/ST/netxduo/crypto_libraries/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/threadx/common/inc/ -I"D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc/ -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32H7xx_Nucleo -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/I-CUBE-Mongoose/Network Library/Mongoose/mongoose_glue.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.o: D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/CM7/I-CUBE-Mongoose/App/mongoose_impl.c Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -D__CCRX__ -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -DUSE_PWR_DIRECT_SMPS_SUPPLY -DUSE_NUCLEO_64 -DTX_INCLUDE_USER_DEFINE_FILE -DNX_SECURE_INCLUDE_USER_DEFINE_FILE -DNX_INCLUDE_USER_DEFINE_FILE -c -I../Core/Inc -I../I-CUBE-Mongoose/App -I"../Middlewares/I-CUBE-Mongoose/Network Library/Mongoose" -I../AZURE_RTOS/App -I../NetXDuo/App -I../NetXDuo/Target -I../../Drivers/BSP/Components/lan8742/ -I"../../Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/netxduo/common/drivers/ethernet/ -I../../Middlewares/ST/netxduo/addons/dhcp/ -I../../Middlewares/ST/netxduo/common/inc/ -I../../Middlewares/ST/netxduo/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/netxduo/nx_secure/inc/ -I../../Middlewares/ST/netxduo/nx_secure/ports/ -I../../Middlewares/ST/netxduo/crypto_libraries/inc/ -I../../Middlewares/ST/netxduo/crypto_libraries/ports/cortex_m7/gnu/inc/ -I../../Middlewares/ST/threadx/common/inc/ -I"D:/gitrepo/Vi-Qi-FSK-Decode/H7_FskDecoder/Middlewares/Third_Party/Cesanta_Network Library/Mongoose" -I../../Middlewares/ST/threadx/ports/cortex_m7/gnu/inc/ -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/BSP/STM32H7xx_Nucleo -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Middlewares/I-CUBE-Mongoose/Network Library/Mongoose/mongoose_impl.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-I-2d-CUBE-2d-Mongoose-2f-Network-20-Library-2f-Mongoose

clean-Middlewares-2f-I-2d-CUBE-2d-Mongoose-2f-Network-20-Library-2f-Mongoose:
	-$(RM) ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.cyclo ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.d ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.o ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose.su ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.cyclo ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.d ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.o ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_fs.su ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.cyclo ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.d ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.o ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_glue.su ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.cyclo ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.d ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.o ./Middlewares/I-CUBE-Mongoose/Network\ Library/Mongoose/mongoose_impl.su

.PHONY: clean-Middlewares-2f-I-2d-CUBE-2d-Mongoose-2f-Network-20-Library-2f-Mongoose

